services:
    app:
        image: rent_buddy_app:latest
        container_name: rent_buddy_app
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        tty: true
        stdin_open: true
        volumes:
            - .:/var/www
        restart: unless-stopped
        networks:
            - rent_buddy

    serve:
        image: rent_buddy_serve:latest
        container_name: rent_buddy_serve
        build:
            context: .
            dockerfile: Dockerfile
            target: serve
        ports:
            - "8000:8000"
        tty: false
        stdin_open: false
        volumes:
            - .:/var/www
        restart: unless-stopped
        networks:
            - rent_buddy

    db:
        image: mysql:8.0
        container_name: rent_buddy_db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - rent_buddy
networks:
    rent_buddy:

volumes:
    dbdata:
        driver: local
